name: NIJZ PCT rules update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/update.yml'
    - 'download.sh'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/update.yml'
    - 'download.sh'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '25 */1 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run download script
      run: ./download.sh

    # Runs a set of commands using the runners shell
    - name: Check git diff
      run: |
        ls -la rules/*
        git status rules/
        git diff rules/

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: Publish NIJZ PCT rule changes to git
      if: github.ref == 'refs/heads/main'
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'NIJZ PCT rules update 🤖'
        rebase: 'true' # pull and rebase before commit
        files: '*.json rules/ valuesets/ signercertificateUpdate.txt'
        name: Sledilnik data scrape bot 🤖
        email: info@sledilnik.org
